apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      name: dev
  template:
    metadata:
      name: dev
      labels:
        name: dev
    spec:
      containers:
        - name: dev
          image: hamda19/seeds-test:latest
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: dev-service
spec:
  selector:
    name: dev
  ports:
    - port: 80
      targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-ingress
  labels:
    name: dev-ingress
spec:
  rules:
    - host: sub.hamda.local
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: dev-service
              port:
                number: 80
