---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: developer
  labels:
    app: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
        - name: dev
          image: hamda19/seeds-test:latest
          ports:
            - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: dev
  namespace: default
spec:
  selector:
    app: dev
  type: NodePort
  ports:
  - name: http
    targetPort: 8080
    port: 80
